company: "PT. Surabaya Autocomp Indonesia"
division: "Software Development"

project_root: "/home/mashupsoat/Project/Work - PT SAI"

git_authors:
  names:
    - "ekyaaa"
    - "Ekya Muhammad Hasfi"
    - "Ekya Muhammad Hasfi Fadlilurrahman"
  emails:
    - "ekyamuhammad@gmail.com"
