name: "Ekya Muhammad Hasfi Fadlilurrahman"
nim: "2341720111"
program: "D-IV Teknik Informatika"
institution: "Politeknik Negeri Malang"
academic_advisor: "Pramana Yoga Saputra, S.Kom., MMT."
field_supervisor: "Anisah Arishandy"
